GET http://localhost:3002/view/customer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ5MTcsImV4cCI6MTY4ODAzNTUxN30.5vl5qrOyc2HTyr9400gPyPhkwmgTWgBswtO1NwEUUa8
###
GET http://localhost:3002/view/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzM4MTQsImV4cCI6MTY4ODAzNDQxNH0.rq8IcBZV5athcpJ0wpPFF1xo1GTKBjf9W-cDA0wQVDs
###
post http://localhost:3002/create/customer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ1MDUsImV4cCI6MTY4ODAzNTEwNX0.uQ-roPmwRuaq_9c2fOcEXhoaoOAUIIZWAERer7P9eqM
Content-Type: application/json

{
    "customername":"dr soo",
    "idproof":"b0221200564"

}
###
post http://localhost:3002/login/admin
Content-Type: application/json

{
    "username":"amir",
    "password":"12345678"
}

###
PUT http://localhost:3002/update/customer/b0221200564
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ1NzksImV4cCI6MTY4ODAzNTE3OX0.tyrwnIcDTjXMKCgnN4GBezUtGnenFMvve4PIKJp5baw
Content-Type: application/json

{
    "cabinno": 3,
    "entrytime": 1018,
    "payment": 21,
    "timespend": 7
}
###
POST http://localhost:3002/create/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ5OTIsImV4cCI6MTY4ODAzNTU5Mn0.WbjaUV57K5-beePR93H_Zb6KScfHpdpw7kKBlrqv0yc
Content-Type: application/json

{
    "computername": "system 5",
    "cabinno": 5,
    "lanportno": 31738124,
    "systemworking": "working", 
    "available": "yes"

}
###
PUT http://localhost:3002/update/computer/system 5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ5OTIsImV4cCI6MTY4ODAzNTU5Mn0.WbjaUV57K5-beePR93H_Zb6KScfHpdpw7kKBlrqv0yc
Content-Type: application/json

{
    "lanportno": 129076927,
    "systemworking": "not working",
    "available": "no"
}
###
DELETE http://localhost:3002/delete/customer/b0221200564
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ1NzksImV4cCI6MTY4ODAzNTE3OX0.tyrwnIcDTjXMKCgnN4GBezUtGnenFMvve4PIKJp5baw
Content-Type: application/json

{
    "idproof": "b0221200564"
}

###
DELETE http://localhost:3002/delete/computer/system 5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODgwMzQ5OTIsImV4cCI6MTY4ODAzNTU5Mn0.WbjaUV57K5-beePR93H_Zb6KScfHpdpw7kKBlrqv0yc
Content-Type: application/json

{
    "computername": "system 5"
}

###
POST http://localhost:3002/logout